jobs:
    include:
        - os: linux
          dist: focal
        - os: osx
          osx_image: xcode10

before_install:
    - source .travis-before-install.sh
    - cd KinKal && mkdir build && cd build
    - source ../../scripts/newBuild.sh prof
    - source setup.sh

script:
    - scons -j 4
    - scons test
