
sudo: required
dist: trusty

services:
  - docker

language: cpp

before_install:
  - wget --no-check-certificate https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  - sudo dpkg -i cvmfs-release-latest_all.deb
  - sudo apt-get update
  - sudo apt-get install cvmfs cvmfs-config-default
  - rm -f cvmfs-release-latest_all.deb

  - sudo /etc/init.d/autofs stop
  - sudo mkdir -p /etc/cvmfs/
  - sudo echo "CVMFS_REPOSITORIES=mu2e.opensciencegrid.org,fermilab.opensciencegrid.org" > default.local
  - sudo echo "CVMFS_HTTP_PROXY=DIRECT" >> default.local
  - sudo mv default.local /etc/cvmfs/default.local

  - sudo cvmfs_config setup
  - sudo mkdir -p /cvmfs/mu2e.opensciencegrid.org
  - sudo mkdir -p /cvmfs/fermilab.opensciencegrid.org

  - mount -t cvmfs mu2e.opensciencegrid.org /cvmfs/mu2e.opensciencegrid.org
  - mount -t cvmfs fermilab.opensciencegrid.org /cvmfs/fermilab.opensciencegrid.org
  
script:
  - docker pull scientificlinux/sl:7
  - cd .. && docker run --name KinKalCI -it scientificlinux/sl:7 -d -v /cvmfs:/cvmfs:ro,shared -v KinKal:/KinKal /bin/bash
  - docker exec -ti KinKalCI /bin/bash -c "cd /KinKal && source .ci-setup.sh"

  
