language: cpp

jobs:
    include:
        - os: linux
          dist: xenial
          sudo: required
          services:
            - docker 
        - os: osx
          osx_image: xcode10
          python: 3.7

before_install:
    - source .travis-before-install.sh

script:
    - source .travis-script.sh
 
