language: cpp

jobs:
    include:
        - os: linux
          dist: bionic

        - os: osx
          osx_image: xcode10

before_install:
    - | 
        # Install dependencies for relevant platform
        if [ $TRAVIS_OS_NAME = 'osx' ]; then
            wget https://root.cern/download/root_v6.22.02.macosx64-10.13-clang100.pkg
            installer -pkg root_v6.22.02.macosx64-10.13-clang100.pkg -target CurrentUserHomeDirectory
            source ~/Applications/root_v6.22.02/bin/thisroot.sh 
        else
            # Ubuntu bionic
            # Install cvmfs and mount sft.cern.ch
            wget --no-check-certificate https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
            sudo dpkg -i cvmfs-release-latest_all.deb

            sudo apt-get update
            sudo apt-get install cvmfs cvmfs-config-default
            rm -f cvmfs-release-latest_all.deb

            sudo /etc/init.d/autofs stop
            sudo mkdir -p /etc/cvmfs/

            echo "CVMFS_REPOSITORIES=sft.cern.ch" > default.local
            echo "CVMFS_HTTP_PROXY=DIRECT" >> default.local
            sudo mv default.local /etc/cvmfs/default.local

            sudo cvmfs_config setup
            sudo mkdir -p /cvmfs/sft.cern.ch
            sudo mount -t cvmfs sft.cern.ch /cvmfs/sft.cern.ch || echo "mount may have failed, will continue anyway"

            source /cvmfs/sft.cern.ch/lcg/views/LCG_98/x86_64-ubuntu1804-gcc7-opt/setup.sh
        fi
script:
    - | 
        # Setup CMake build directory
        which cmake
        cmake --version
        
        cd .. # Out of source build
        rm -rf KinKal-build || echo ""
        mkdir KinKal-build && cd KinKal-build
        cmake ../KinKal -DCMAKE_BUILD_TYPE=Release
    - make -j 8
    - env CTEST_OUTPUT_ON_FAILURE=1 make test
