language: cpp

jobs:
    include:
        - os: linux
          dist: bionic
          sudo: required
        - os: osx
          osx_image: xcode10
          python: 3.7

before_install:
    - source .travis-before-install.sh

script:
    - |
        rm -rf build || echo ""
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j 8
    - env CTEST_OUTPUT_ON_FAILURE=1 make test
