#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('build_helper')

helper=build_helper(env);

mainlib = helper.make_mainlib ( ['GenVector' 
                                ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
