#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('build_helper')
#rootlibs  = env['ROOTLIBS']

helper=build_helper();

mainlib = helper.make_mainlib ( env,
                                [ 
                                ] )

#helper.make_bin( "test", [ 'test', rootlibs ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
