#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('build_helper')

helper=build_helper(env);

# key : value are name of executable : link list
# If the required link list is empty, no entry is needed in this structure.
linkLists = {
 'pi'      : [ 'BTrk_BaBar', 'CLHEP' ]
}

helper.make_unit_tests ( linkLists )

helper.run_unit_tests()


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
